spring.application.name=mini-project-task-manager

server.port=8080

<<<<<<< HEAD
# secret profile active
spring.profiles.active=secret

spring.datasource.url=jdbc:mysql://localhost:3306/k5_iot_springboot
=======
# spring profile active
spring.profiles.active=secret

#spring.datasource.url=jdbc:mysql://localhost:3306/k5_iot_springboot
>>>>>>> develop
spring.datasource.username=root

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
<<<<<<< HEAD
#validate -- picky
=======
>>>>>>> develop

# logging.file.name=logs/app.log
logging.level.root=INFO

# ======= JWT =======
<<<<<<< HEAD
=======

>>>>>>> develop
jwt.secret=1234567890qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM1234567890

# 1h = 3600000ms
jwt.expiration=3600000
<<<<<<< HEAD

jwt.clock-skew-seconds=60
# few seconds may be different from each country.
=======
jwt.clock-skew-seconds=60
>>>>>>> develop

# ======= CORS =======
cors.allowed-origins=*
cors.allowed-headers=*
cors.allowed-methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
cors.exposed-headers=Authorization,Set-cookie

<<<<<<< HEAD
# ======= Dev Option =======
=======
# ====== Dev Option ======
>>>>>>> develop
security.h2-console=true